service_name: travis-ci
dist: trusty
sudo: false
language: elixir
elixir:
  - '1.9'
otp_release:
  - '22.1'
install:
  - MIX_ENV=test mix do local.rebar --force, local.hex --force, deps.get
script:
  - MIX_ENV=test mix do compile, test
after_script:
  - MIX_ENV=test mix coveralls.travis
notifications:
  email:
    - mark@keele.codes
